version: "3"
services:
  db:
    image: mysql:latest 
    container_name: "db_container"
    stdin_open : true
    tty : true
    volumes:
      - ./:/app
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "30000:3306"
  
  app:
    # links : # 다른 서비스 접근 가능 
    #  - db 
    depends_on: # 다른 서비스 먼저 실행
      - db
    container_name : "app_container"
    volumes:
      - ./:/app
    build : . # 도커파일 경로 지정
    # command : bash -c python /app/src/app.py # Dockerfile CMD overriding !! 
    environment: # 환경 변수 설정
      - FLASK_ENV=/development
      - FLASK_APP=/app/src/app.py 
    ports:
      - 5000:5000