version: "3"
services:
  db:
    image : nouchka/sqlite3:latest
    container_name  : "db_container"
    stdin_open : true
    tty : true
    volumes :
      - ./:/app
  
  app:
    image : "python:3.8"
    # links : # 다른 서비스 접근 가능 
    #  - db 
    depends_on: # 다른 서비스 먼저 실행
      - db
    container_name : "app_container"
    volumes:
      - ./:/app
    build : . # 도커파일 경로 지정
    environment: # 환경 변수 설정
      - FLASK_ENV=/development
      - FLASK_APP=/app/src/app.py
      - DATABASE=/app/test.db
    ports:
      - 5000:5000